Add support to read/write space-padded fixed-length strings
gijzelaerr/python-snap7 pull request #378
Opened 2022-08-01 07:45 UTC by vmsh0

Following the discussion in issue #375, I'm offering this PR with the modifications we are using internally to support the datatype.

A recap of what this is, adapted from the commit message:

These strings are not part of the official s7comm specification, but
they are commonly found in real-world systems. They simply consist of a
byte array that contains characters forming a string, padded on the
right with spaces (ascii 32) when the string length is shorter than the
array.

This commit adds support for reading and writing, as well as usage in
tables (snap7.util.DB), and unit tests.

2022-08-01 07:54 UTC, vmsh0 commented
I kept this separate from #377 in case you only want the fix (and not this feature), but if you wish I can both changes on your last master and offer a single pull request with both things.

2022-08-03 08:39 UTC, gijzelaerr requested changes
i don't think this affects any existing usage, so I don't object adding this to the lib. one small comment about type checking.

2022-08-03 08:39 UTC, gijzelaerr commented on snap7/util.py
> +        raise TypeError(f"Value value:{value} is not from Type string")
to be consistent, I think validating the type should be handled by a type checker like mypy, and not be done manually.

2022-08-03 13:19 UTC, vmsh0 commented
I have made the requested change as well as fixed the reported linting issues.

2022-08-03 13:30 UTC, merged